# Generated by Django 4.2.7 on 2023-12-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addComment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcomment',
            name='topic_name',
            field=models.CharField(max_length=500),
        ),
    ]
